### ISSUE TITLE
分类问题

### ISSUE THREAD

**Issue by liuhuancom** [anshengme/July#2]
分类怎么不是无限分类的

**Comment by anshengme** [comment]
你说的无限分类是什么意思呢、

**Comment by liuhuancom** [comment]
就像WordPress里面的分类和标签一样 
WordPress里面的分类是有层级的 
标签是就只有一级

**Comment by anshengme** [comment]
明白了，我这个分类只有一级，可以隶属多个分类，标签确实只有一级，我会考虑分级的问题

**Comment by liuhuancom** [comment]
谢谢 相互学习
