### ISSUE TITLE
后台管理，数据呈现是否应该按需请求？

### ISSUE THREAD

**Issue by JoeyFFF** [anshengme/July#3]
阅读源码后发现，数据由后端请求时直接全部丢出为html tr，再由前端DataTables整理。
当数据量庞大时是否会造成性能问题？

**Comment by JoeyFFF** [comment]
admin/article/list/
admin/tag/
admin/categories/
等

**Comment by anshengme** [comment]
yes，因为刚开始数据量不是很大，多以并没有直接写分页，既然你提出这个问题了， 那么下个版本会在后端实现分页功能。
