### ISSUE TITLE
admin这个模块是如何实现的？

### ISSUE THREAD

**Issue by willhunger** [anshengme/July#5]
想问一下楼主实现的具体过程？

**Comment by anshengme** [comment]
这个就是一个增删改查的功能，参考下源码，比较简单，并不是类似django自带的admin

**Comment by willhunger** [comment]
@anshengme 
我打算直接用django自带的admin吧。
我还有一个问题，就是老师给我的一个挑战性的问题。
就是在注册用户的时候，不再数据库存储密码的哈希值，而是存储一个token来实现用户的身份认证，
这套登陆注册系统要包括邮件激活账户系统，还有找回密码功能，我要怎么去实现呢？
请教一下您

**Comment by anshengme** [comment]
@willhunger 

1. Django自带的Admin确实好用，但是其丑无比，之前我就是用自带的admin；
2. 建议你去了解一下`djangorestframework`，你说的这些问题他都可以实现，用户登录成功之后返回一个`Token`，每次打开其他页面的时候带着这个`Token`。

**Comment by willhunger** [comment]
@anshengme  谢谢您了，以后还有什么问题还请多指教噢

**Comment by willhunger** [comment]
@anshengme 
对了，还有一个问题，如果不是用内置的admin，用户和组的管理是否还可以使用内置的方法呢？
