### ISSUE TITLE
关于上次token的问题

### ISSUE THREAD

**Issue by willhunger** [anshengme/July#7]
因为在你博客没看到你的回复，所以我直接来这里了
这篇文章下面,https://blog.ansheng.me/article/django-rest-framework-token-expiring/
我想问一下博主如何把token放到request中，而且该如何写这个view？ 有点

**Comment by anshengme** [comment]
博客的评论系统还不是很完善，所以并没有关注太多，关于你这个问题，我给你一段代码，你理解下：

View代码：

```python
class TestView(APIView):
    authentication_classes = (BasicAuthentication,)
    permission_classes = (IsAuthenticated,)

    def get(self, request, uid):        
        return Response()
```

关于如何发送ajax请求，请在HTTP请求头中加入一下字段：

```html
Authorization: Token 55e1d217fab0fcc53e60d79ebf8ca49ed81ecf1c
```

然后rest会拿到这个token去获取对应的用户，如果获取到了，就会返回用户的实例，否则就报错。
