### ISSUE TITLE
安装  django-pure-pagination==0.3.0 失败

### ISSUE THREAD

**Issue by ghost7890** [anshengme/July#8]
下为错误提示，目前还未解决
Collecting django-pure-pagination==0.3.0 (from -r requirements.txt (line 5))
  Using cached django-pure-pagination-0.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-_rx50w08/django-pure-pagination/setup.py", line 5, in <module>
        README = readme.read()
      File "/usr/local/virtualenv/July/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 672: ordinal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-_rx50w08/django-pure-pagination/

问题已解决：
LANG=en_US.UTF-8 pip install django-pure-pagination
链接为：https://github.com/jamespacileo/django-pure-pagination/issues/40

**Comment by anshengme** [comment]
Good
